version: '3'

includes:
  dev:
    taskfile: ../.task/taskfile.yaml
    vars:
      app_env: 'dev'
      app_name: 'hello'
  prd:
    taskfile: ../.task/taskfile.yaml
    vars:
      app_env: 'prd'
      app_name: 'hello'
