name: remind

services:
  app:
    build:
      context: .
      target: local
    image: remind:local
    pull_policy: build
    ports:
      - 8080
    env_file:
      - path: .env
        required: true

  curl:
    image: curlimages/curl:8.10.1
    depends_on:
      app:
        condition: service_started
        restart: true
    command: ["http://app:8080/2015-03-31/functions/function/invocations", "-d", "{}"]
